backup_y_accion:
  runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Crear copia de seguridad
        run: |
          mkdir -p backup
          cp -r datos backup/

      - name: Comprimir backup
        run: |
          tar -czf backup.tar.gz backup

      - name: Subir artefacto
        uses: actions/upload-artifact@v5
        with:
          name: copia-seguridad
          path: backup.tar.gz
      